### ISSUE TITLE
Update code to Swift 2.0

### ISSUE THREAD

**Issue by Ewg777** [Mailcloud/swift-serializer#16]
'reflect' is unavailable in xcode 7 beta 4

**Comment by briananderson1222** [comment]
Hey I added a PR (even though it should get moved to a 'swift-2.0' branc when one becomes available) https://github.com/Mailcloud/swift-serializer/pull/17 . Hope this is helpful and I welcome feedback

**Comment by turowicz** [comment]
This issue will be closed when we manage to integrate swift-2.0 branch into our projects.

**Comment by MaximShoustin** [comment]
fix for Swift2 Xcode7:

public class Serializable : NSObject{
    
    
     public func toDictionary() -> NSDictionary {
        let propertiesDictionary = NSMutableDictionary()
        //let mirror = reflect(self)
        let mirror = Mirror(reflecting: self)
        
        for c in mirror.children {
            
            let propName = c.label
            let childMirror = c.value
        
        
//        for i in 1..<mirror..count {
//            let (propName, childMirror) = mirror[i]
        
            if let propValue: AnyObject = self.unwrap(childMirror) as? AnyObject {
                if let serializablePropValue = propValue as? Serializable {
                    propertiesDictionary.setValue(serializablePropValue.toDictionary(), forKey: propName!)
                } else if let arrayPropValue = propValue as? [Serializable] {
                    var subArray = [NSDictionary]()
                    for item in arrayPropValue {
                        subArray.append(item.toDictionary())
                    }
                    
                    propertiesDictionary.setValue(subArray, forKey: propName!)
                } else if propValue is Int || propValue is Double || propValue is Float {
                    propertiesDictionary.setValue(propValue, forKey: propName!)
                } else if let dataPropValue = propValue as? NSData {
                    propertiesDictionary.setValue(dataPropValue.base64EncodedStringWithOptions(.Encoding64CharacterLineLength), forKey: propName!)
                } else if let datePropValue = propValue as? NSDate {
                    propertiesDictionary.setValue(datePropValue.timeIntervalSince1970, forKey: propName!)
                } else if let boolPropValue = propValue as? Bool {
                    propertiesDictionary.setValue(boolPropValue, forKey: propName!)
                } else {
                    propertiesDictionary.setValue(propValue, forKey: propName!)
                }
            }
        }
        
        return propertiesDictionary
    }

extension Serializable {
   private func unwrap(any: Any) -> Any? {
    
        let mi = Mirror(reflecting: any)
        
        if mi.descendant("Some") == nil {
            return any
        }
        
        if mi.children.count == 0 {
            return nil
        }
        
        let (_, some) = mi.children.first!
        
        return some
    }
}

**Comment by alvaro1728** [comment]
Thanks @MaximShoustin!

**Comment by alvaro1728** [comment]
By the way, I added an extension to the Array type so that you can directly serialize an array of Serializables.  For example, given:

    let myArray = [mySerializable1, mySerializable2, ...]

Now you can say:

    let json = myArray.toJsonString()!

Here's the code:

extension Array where Element: Serializable {
    /**
    Converts the array to JSON.
    
    :returns: The array as JSON, wrapped in NSData.
    */
    public func toJson(prettyPrinted : Bool = false) -> NSData? {
        var subArray = [NSDictionary]()
        for item in self {
            subArray.append(item.toDictionary())
        }
        
        if NSJSONSerialization.isValidJSONObject(subArray) {
            do {
                let json = try NSJSONSerialization.dataWithJSONObject(subArray, options: (prettyPrinted ? .PrettyPrinted : NSJSONWritingOptions()))
                return json
            } catch {
                //currently swift will not catch NSInvalidArgumentException exception
                print("ERROR: Unable to serialize json, error: \(error)")
                NSNotificationCenter.defaultCenter().postNotificationName("CrashlyticsLogNotification", object: self, userInfo: ["string": "unable to serialize json, error: \(error)"])
            }
        }
        
        return nil
    }
    
    /**
    Converts the array to a JSON string.
    
    :returns: The array as a JSON string.
    */
    public func toJsonString(prettyPrinted : Bool = false) -> String? {
        if let jsonData = toJson(prettyPrinted) {
            return NSString(data: jsonData, encoding: NSUTF8StringEncoding) as String?
        }
        
        return nil
    }
}

Cheers!
Alvaro

**Comment by pabloa** [comment]
I added this patch https://github.com/Mailcloud/swift-serializer/pull/27 I did not read this ticket before start to work :)
