### ISSUE TITLE
Maintainers wanted!

### ISSUE THREAD

**Issue by turowicz** [Mailcloud/swift-serializer#28]
Hey guys

As you have probably noticed this git repo isn't well maintained: code is not being reviewed, requests are not merged etc. 

This is all because because we have shifted our development focus away from iOS/Swift. That said we are happy to accept anyone who wish to become a contributor to the project in terms of code review and PR merging.

Please apply below this post.

**Comment by sjturley** [comment]
Hi, I'd like to be a maintainer.  I have over a decade of dev experience and an MS in CS.  I'm expert in TDD and gain help the PRs come in with proper testing.  I'd also like to help get Travis CI setup for this project.  Hope I can help!

--Steve

**Comment by turowicz** [comment]
Adding you to contributors Steve. The biggest challenge we have here is making sure the code works and all tests pass. Feel free to introduce any CI you think is right.

**Comment by turowicz** [comment]
@sjturley can you email me at admin@mailcloud.com?
