### ISSUE TITLE
XCTest

### ISSUE THREAD

**Issue by PierreLouisBresson** [Mailcloud/swift-serializer#9]
Hi,

I'm new to swift, I try to create my first app and to do so I'm trying to save a class (with strings, int and an array of another class) to .json file (so I when app is closed/opened, data remains). I found your serializer very interesting but when I try to import XCTest, I have this issue : 
![capture d ecran 2015-05-11 a 12 03 44](https://cloud.githubusercontent.com/assets/8709134/7562759/2ba952f0-f7d7-11e4-95f7-935ea423fb04.png)

I also found errors on your Serializable.swift : 
![capture d ecran 2015-05-11 a 12 01 02](https://cloud.githubusercontent.com/assets/8709134/7562849/15402c7c-f7d8-11e4-8cbf-082c41db9734.png)

Here is how I fixed that :     

public func toDictionary() -> NSDictionary {
        var aClass : AnyClass? = self.dynamicType
        var propertiesCount : CUnsignedInt = 0
        let propertiesInAClass : UnsafeMutablePointer<objc_property_t> = class_copyPropertyList(aClass, &propertiesCount)
        var propertiesDictionary : NSMutableDictionary = NSMutableDictionary()
        
        for var i = 0; i < Int(propertiesCount); i++ {
            var property = propertiesInAClass[i]
            var propName = NSString(CString: property_getName(property), encoding: NSUTF8StringEncoding)!
            var propType = property_getAttributes(property)
            var propValue : AnyObject! = self.valueForKey(propName as String);
            
            if propValue is Serializable {
                propertiesDictionary.setValue((propValue as! Serializable).toDictionary(), forKey: propName as String)
            } else if propValue is Array<Serializable> {
                var subArray = Array<NSDictionary>()
                for item in (propValue as! Array<Serializable>) {
                    subArray.append(item.toDictionary())
                }
                propertiesDictionary.setValue(subArray, forKey: propName as String)
            } else if propValue is Double {
                propertiesDictionary.setValue((propValue as! Double), forKey: propName as String)
            } else if propValue is Int {
                propertiesDictionary.setValue((propValue as! Int), forKey: propName as String)
            } else if propValue is Float {
                propertiesDictionary.setValue((propValue as! Float), forKey: propName as String)
            } else if propValue is NSData {
                propertiesDictionary.setValue((propValue as! NSData).base64EncodedStringWithOptions(nil), forKey: propName as String)
            } else if propValue is Bool {
                propertiesDictionary.setValue((propValue as! Bool).boolValue, forKey: propName as String)
            } else {
                propertiesDictionary.setValue(propValue, forKey: propName as String)
            }
        }
        
        // class_copyPropertyList retaints all the
        propertiesInAClass.dealloc(Int(propertiesCount))
        
        return propertiesDictionary
    }

Thanks for reading !

**Comment by mpavlinsky** [comment]
You can't import XCTest in a file that is not part of your test target.

**Comment by PierreLouisBresson** [comment]
Is any "example" project ? I found nothing and it will help me a lot to understand how swift-serializer is working.

**Comment by turowicz** [comment]
download the swift file, include in your project, inherit the Serializable class and start using the ToJson functionality - that's all

**Comment by PierreLouisBresson** [comment]
Found how it's working, thanks for answers.
